In [4]:
import pandas as pd

# 1. Load the dataset from the URL into a DataFrame named 'data'
url = "https://docs.google.com/spreadsheets/d/1zLGcNoattvIPSjkHYF9lzn6R_kGxGWqC/export?format=csv"
data = pd.read_csv(url)

In [26]:
df = pd.DataFrame(data)
print(df)

       transaction_id StockCode                            item_name  \
0              536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1              536365     71053                  WHITE METAL LANTERN
2              536365    84406B       CREAM CUPID HEARTS COAT HANGER
3              536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4              536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...               ...       ...                                  ...
541904         581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905         581587     22899         CHILDREN'S APRON DOLLY GIRL
541906         581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907         581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908         581587     22138        BAKING SET 9 PIECE RETROSPOT

        order_quantity transaction_date  item_price  CustomerID  \
0                    6     12/1/10 8:26        2.55     17850.0
1                    6     12/1/10 8:26        3.39     17850.0
2                    8     12/1/10 8:26        2.75     17850.0
3                    6     12/1/10 8:26        3.39     17850.0
4                    6     12/1/10 8:26        3.39     17850.0
...                ...              ...         ...         ...
541904              12    12/9/11 12:50        0.85     12680.0
541905               6    12/9/11 12:50        2.10     12680.0
541906               4    12/9/11 12:50        4.15     12680.0
541907               4    12/9/11 12:50        4.15     12680.0
541908               3    12/9/11 12:50        4.95     12680.0

               Country
0       United Kingdom
1       United Kingdom
2       United Kingdom
3       United Kingdom
4       United Kingdom
...                ...
541904          France
541905          France
541906          France
541907          France
541908          France

[541909 rows x 8 columns]

In [27]:
print("First 5 Rows:")
print(df.head())

First 5 Rows:
  transaction_id StockCode                            item_name  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

   order_quantity transaction_date  item_price  CustomerID         Country
0               6     12/1/10 8:26        2.55     17850.0  United Kingdom
1               6     12/1/10 8:26        3.39     17850.0  United Kingdom
2               8     12/1/10 8:26        2.75     17850.0  United Kingdom
3               6     12/1/10 8:26        3.39     17850.0  United Kingdom
4               6     12/1/10 8:26        3.39     17850.0  United Kingdom

In [28]:
print("\nLast 3 Rows:")
print(df.tail(3))

Last 3 Rows:
       transaction_id StockCode                        item_name  \
541906         581587     23254    CHILDRENS CUTLERY DOLLY GIRL
541907         581587     23255  CHILDRENS CUTLERY CIRCUS PARADE
541908         581587     22138    BAKING SET 9 PIECE RETROSPOT

        order_quantity transaction_date  item_price  CustomerID Country
541906               4    12/9/11 12:50        4.15     12680.0  France
541907               4    12/9/11 12:50        4.15     12680.0  France
541908               3    12/9/11 12:50        4.95     12680.0  France

In [29]:
print("Shape of DataFrame:")
print(df.shape)

Shape of DataFrame:
(541909, 8)

In [30]:
print("DataFrame Info:")
df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    541909 non-null  object
 1   StockCode         541909 non-null  object
 2   item_name         540455 non-null  object
 3   order_quantity    541909 non-null  int64
 4   transaction_date  541909 non-null  object
 5   item_price        541909 non-null  float64
 6   CustomerID        406829 non-null  float64
 7   Country           541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [31]:
print("Descriptive Statistics (Numerical Columns):")
print(df.describe())

Descriptive Statistics (Numerical Columns):
       order_quantity     item_price     CustomerID
count   541909.000000  541909.000000  406829.000000
mean         9.552250       4.611114   15287.690570
std        218.081158      96.759853    1713.600303
min     -80995.000000  -11062.060000   12346.000000
25%          1.000000       1.250000   13953.000000
50%          3.000000       2.080000   15152.000000
75%         10.000000       4.130000   16791.000000
max      80995.000000   38970.000000   18287.000000

In [32]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['transaction_id', 'StockCode', 'item_name', 'order_quantity',
       'transaction_date', 'item_price', 'CustomerID', 'Country'],
      dtype='object')

In [33]:
print("Data Types:")
print(df.dtypes)

Data Types:
transaction_id       object
StockCode            object
item_name            object
order_quantity        int64
transaction_date     object
item_price          float64
CustomerID          float64
Country              object
dtype: object

In [34]:
print("Descriptive Statistics (All Columns):")
print(df.describe(include='all'))

Descriptive Statistics (All Columns):
       transaction_id StockCode                           item_name  \
count          541909    541909                              540455
unique          25900      4070                                4223
top            573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER
freq             1114      2313                                2369
mean              NaN       NaN                                 NaN
std               NaN       NaN                                 NaN
min               NaN       NaN                                 NaN
25%               NaN       NaN                                 NaN
50%               NaN       NaN                                 NaN
75%               NaN       NaN                                 NaN
max               NaN       NaN                                 NaN

        order_quantity transaction_date     item_price     CustomerID  \
count    541909.000000           541909  541909.000000  406829.000000
unique             NaN            23260            NaN            NaN
top                NaN   10/31/11 14:41            NaN            NaN
freq               NaN             1114            NaN            NaN
mean          9.552250              NaN       4.611114   15287.690570
std         218.081158              NaN      96.759853    1713.600303
min      -80995.000000              NaN  -11062.060000   12346.000000
25%           1.000000              NaN       1.250000   13953.000000
50%           3.000000              NaN       2.080000   15152.000000
75%          10.000000              NaN       4.130000   16791.000000
max       80995.000000              NaN   38970.000000   18287.000000

               Country
count           541909
unique              38
top     United Kingdom
freq            495478
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN

In [35]:
rename_columns = {
    'InvoiceNo': 'transaction_id',
    'Description': 'item_name',
    'Quantity': 'order_quantity',
    'UnitPrice': 'item_price',
    'InvoiceDate': 'transaction_date'
}

df.rename(columns=rename_columns, inplace=True)

print(df.columns)

Index(['transaction_id', 'StockCode', 'item_name', 'order_quantity',
       'transaction_date', 'item_price', 'CustomerID', 'Country'],
      dtype='object')

In [23]:
df.head(5)

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [24]:
df.loc[:9, ['item_name', 'item_price']]

                             item_name  item_price
0   WHITE HANGING HEART T-LIGHT HOLDER        2.55
1                  WHITE METAL LANTERN        3.39
2       CREAM CUPID HEARTS COAT HANGER        2.75
3  KNITTED UNION FLAG HOT WATER BOTTLE        3.39
4       RED WOOLLY HOTTIE WHITE HEART.        3.39
5         SET 7 BABUSHKA NESTING BOXES        7.65
6    GLASS STAR FROSTED T-LIGHT HOLDER        4.25
7               HAND WARMER UNION JACK        1.85
8            HAND WARMER RED POLKA DOT        1.85
9        ASSORTED COLOUR BIRD ORNAMENT        1.69

In [25]:
filtered_data = df.loc[df['order_quantity'] > 1]

filtered_data.head()

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [36]:
filtered_data = df.loc[
    (df['item_name'] == 'WHITE HANGING HEART T-LIGHT HOLDER') &
    (df['order_quantity'] == 6)
]

# Display all matching rows
filtered_data

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 9:02,2.55,17850.0,United Kingdom
66,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 9:32,2.55,17850.0,United Kingdom
278,536396,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 10:51,2.55,17850.0,United Kingdom
935,536502,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 12:36,2.95,16552.0,United Kingdom
...,...,...,...,...,...,...,...,...
533124,581014,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/7/11 9:34,2.95,16458.0,United Kingdom
534570,581163,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/7/11 14:34,2.95,12747.0,United Kingdom
534876,581174,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/7/11 15:08,2.95,13769.0,United Kingdom
537852,581356,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/8/11 12:28,2.95,17830.0,United Kingdom
540217,581472,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/8/11 19:55,2.95,15796.0,United Kingdom

In [38]:
filtered_data = df.loc[
    (df['item_name'] == 'WHITE METAL LANTERN') |
    (df['order_quantity'] < 5)
]

# Display all matching rows
filtered_data.head(5)

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/10 8:26,7.65,17850.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/10 8:34,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/10 8:34,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/10 8:34,5.95,13047.0,United Kingdom

In [39]:
df.iloc[:, :3]

       transaction_id StockCode                            item_name
0              536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1              536365     71053                  WHITE METAL LANTERN
2              536365    84406B       CREAM CUPID HEARTS COAT HANGER
3              536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4              536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...               ...       ...                                  ...
541904         581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905         581587     22899         CHILDREN'S APRON DOLLY GIRL
541906         581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907         581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908         581587     22138        BAKING SET 9 PIECE RETROSPOT

[541909 rows x 3 columns]

In [40]:
sorted_data = df.sort_values(by='item_price', ascending=True)

# Display the first 5 rows
sorted_data.head()

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,8/12/11 14:51,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,8/12/11 14:52,-11062.06,NaN,United Kingdom
313647,564530,22678,FRENCH BLUE METAL DOOR SIGN 3,3,8/25/11 14:57,0.00,NaN,United Kingdom
115808,546140,21527,damages,-30,3/9/11 16:35,0.00,NaN,United Kingdom
516189,579880,22947,NaN,5,11/30/11 17:14,0.00,NaN,United Kingdom

In [41]:
sorted_data = df.sort_values(by='order_quantity', ascending=False)

sorted_data.head()

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/11 9:15,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/11 10:01,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,11/25/11 15:57,0.00,13256.0,United Kingdom
74614,542504,37413,NaN,5568,1/28/11 12:03,0.00,NaN,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/11 12:26,0.21,12901.0,United Kingdom

In [42]:
print(df['item_name'].nunique())

4223

In [ ]:
print(df['item_name'].unique())

In [43]:
print(df['Country'].nunique())

38